// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5fyESee-BCArtLX3wsmRC1M8ZMVMyX1M',
    appId: '1:761036978549:ios:b0e333aeeae84ddbd03b3c',
    messagingSenderId: '761036978549',
    projectId: 'agridroneapp-38df2',
    storageBucket: 'agridroneapp-38df2.firebasestorage.app',
    iosBundleId: 'com.example.agriDroneAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5fyESee-BCArtLX3wsmRC1M8ZMVMyX1M',
    appId: '1:761036978549:ios:b0e333aeeae84ddbd03b3c',
    messagingSenderId: '761036978549',
    projectId: 'agridroneapp-38df2',
    storageBucket: 'agridroneapp-38df2.firebasestorage.app',
    iosBundleId: 'com.example.agriDroneAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1o6xzfW29zsVptj3Eo006XFQ03TbAkvQ',
    appId: '1:761036978549:web:024f275588298457d03b3c',
    messagingSenderId: '761036978549',
    projectId: 'agridroneapp-38df2',
    authDomain: 'agridroneapp-38df2.firebaseapp.com',
    storageBucket: 'agridroneapp-38df2.firebasestorage.app',
    measurementId: 'G-EZF1B2XV5P',
  );
}
